apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xsystem.cnp.example.org
spec:
  group: cnp.example.org
  names:
    kind: XSystem
    plural: xsystems
  claimNames:
    kind: System
    plural: systems
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec: {}